
language: node_js
node_js:
  - 12

branches:
  only:
    - master

script:
  - yarn install  
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: dist 
